//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.SwServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pe.solusage.com/", ConfigurationName="SwServiceReference.WsAuth")]
    public interface WsAuth {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://pe.solusage.com/WsAuth/authTestRequest", ReplyAction="http://pe.solusage.com/WsAuth/authTestResponse")]
        Cliente.SwServiceReference.authTestResponse authTest(Cliente.SwServiceReference.authTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pe.solusage.com/WsAuth/authTestRequest", ReplyAction="http://pe.solusage.com/WsAuth/authTestResponse")]
        System.Threading.Tasks.Task<Cliente.SwServiceReference.authTestResponse> authTestAsync(Cliente.SwServiceReference.authTestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authTest", Namespace="http://pe.solusage.com/", Order=0)]
        public Cliente.SwServiceReference.authTestRequestBody Body;
        
        public authTestRequest() {
        }
        
        public authTestRequest(Cliente.SwServiceReference.authTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class authTestRequestBody {
        
        public authTestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authTestResponse", Namespace="http://pe.solusage.com/", Order=0)]
        public Cliente.SwServiceReference.authTestResponseBody Body;
        
        public authTestResponse() {
        }
        
        public authTestResponse(Cliente.SwServiceReference.authTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class authTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public authTestResponseBody() {
        }
        
        public authTestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsAuthChannel : Cliente.SwServiceReference.WsAuth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsAuthClient : System.ServiceModel.ClientBase<Cliente.SwServiceReference.WsAuth>, Cliente.SwServiceReference.WsAuth {
        
        public WsAuthClient() {
        }
        
        public WsAuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsAuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.SwServiceReference.authTestResponse Cliente.SwServiceReference.WsAuth.authTest(Cliente.SwServiceReference.authTestRequest request) {
            return base.Channel.authTest(request);
        }
        
        public string authTest() {
            Cliente.SwServiceReference.authTestRequest inValue = new Cliente.SwServiceReference.authTestRequest();
            inValue.Body = new Cliente.SwServiceReference.authTestRequestBody();
            Cliente.SwServiceReference.authTestResponse retVal = ((Cliente.SwServiceReference.WsAuth)(this)).authTest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.SwServiceReference.authTestResponse> Cliente.SwServiceReference.WsAuth.authTestAsync(Cliente.SwServiceReference.authTestRequest request) {
            return base.Channel.authTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.SwServiceReference.authTestResponse> authTestAsync() {
            Cliente.SwServiceReference.authTestRequest inValue = new Cliente.SwServiceReference.authTestRequest();
            inValue.Body = new Cliente.SwServiceReference.authTestRequestBody();
            return ((Cliente.SwServiceReference.WsAuth)(this)).authTestAsync(inValue);
        }
    }
}
